* minor: more pronounced script error messages

diff --git a/host/tarball/bin/ae3 b/host/tarball/bin/ae3
--- a/host/tarball/bin/ae3
+++ b/host/tarball/bin/ae3
@@ -25,7 +25,7 @@ if [ ! -x "/usr/local/share/ae3/bin/$COMMAND" ]; then
 	UserRequireOperator
 	
 	PrintDefault
-	>&2 echo "Unknown command: $COMMAND"
+	>&2 echo "ERROR: Unknown command: $COMMAND"
 	exit 1
 fi
 
diff --git a/host/tarball/share/ae3/bin/config/assert b/host/tarball/share/ae3/bin/config/assert
--- a/host/tarball/share/ae3/bin/config/assert
+++ b/host/tarball/share/ae3/bin/config/assert
@@ -22,7 +22,8 @@ case "$1" in
 		;;
 	ALL)
 		;;
-	*) echo "Invalid optimization goal, must be one of: NONE, NORMAL, MOST or ALL"
+	*) 
+		echo "ERROR: Invalid assertion mode, must be one of: NONE, NORMAL, MOST or ALL" >&2
 		exit 1
 		;;
 esac
diff --git a/host/tarball/share/ae3/bin/config/daemon b/host/tarball/share/ae3/bin/config/daemon
--- a/host/tarball/share/ae3/bin/config/daemon
+++ b/host/tarball/share/ae3/bin/config/daemon
@@ -18,7 +18,8 @@ case "$1" in
 		;;
 	DISABLE)
 		;;
-	*) echo "Invalid daemon mode, must be one of: ENABLE or DISABLE"
+	*) 
+		echo "ERROR: Invalid daemon mode, must be one of: ENABLE or DISABLE" >&2
 		exit 1
 		;;
 esac
diff --git a/host/tarball/share/ae3/bin/config/logging b/host/tarball/share/ae3/bin/config/logging
--- a/host/tarball/share/ae3/bin/config/logging
+++ b/host/tarball/share/ae3/bin/config/logging
@@ -22,7 +22,8 @@ case "$1" in
 		;;
 	MINIMAL)
 		;;
-	*) echo "Invalid logging level, must be one of: DEVEL, DEBUG, NORMAL or MINIMAL"
+	*) 
+		echo "ERROR: Invalid logging level, must be one of: DEVEL, DEBUG, NORMAL or MINIMAL" >&2
 		exit 1
 		;;
 esac
diff --git a/host/tarball/share/ae3/bin/config/optimize b/host/tarball/share/ae3/bin/config/optimize
--- a/host/tarball/share/ae3/bin/config/optimize
+++ b/host/tarball/share/ae3/bin/config/optimize
@@ -20,7 +20,8 @@ case "$1" in
 		;;
 	SPEED)
 		;;
-	*) echo "Invalid optimization goal, must be one of: DEFAULT, SIZE or SPEED"
+	*) 
+		echo "ERROR: Invalid optimization goal, must be one of: DEFAULT, SIZE or SPEED" >&2
 		exit 1
 		;;
 esac
diff --git a/host/tarball/share/ae3/bin/config/profile b/host/tarball/share/ae3/bin/config/profile
--- a/host/tarball/share/ae3/bin/config/profile
+++ b/host/tarball/share/ae3/bin/config/profile
@@ -20,7 +20,8 @@ case "$1" in
 		;;
 	JMX)
 		;;
-	*) echo "Invalid profiling mode, must be one of: OFF, YJP or JMX"
+	*) 
+		echo "ERROR: Invalid profiling mode, must be one of: OFF, YJP or JMX" >&2
 		exit 1
 		;;
 esac
diff --git a/host/tarball/share/ae3/bin/config/ram b/host/tarball/share/ae3/bin/config/ram
--- a/host/tarball/share/ae3/bin/config/ram
+++ b/host/tarball/share/ae3/bin/config/ram
@@ -19,5 +19,5 @@ if echo $1 | fgrep -qoE "\b([0-9]*?)(k|m|g)\b"; then
 	exit 0
 fi
 
-echo "Invalid memory allocation specification, use like: 512m, 768m, 2g..."
+echo "ERROR: Invalid memory allocation specification, use like: 512m, 768m, 2g..." >&2
 exit 1
diff --git a/host/tarball/share/ae3/bin/console b/host/tarball/share/ae3/bin/console
--- a/host/tarball/share/ae3/bin/console
+++ b/host/tarball/share/ae3/bin/console
@@ -7,7 +7,7 @@ set -e
 UserRequireRoot
 
 if [ ! -e "$AE3_STDIN" ]; then
-	echo "Cannot connect to daemon's console: Looks like daemon is not running!"
+	echo "ERROR: Cannot connect to daemon's console: Looks like daemon is not running!" >&2
 	exit 1
 fi
 
diff --git a/host/tarball/share/ae3/bin/setup/operator b/host/tarball/share/ae3/bin/setup/operator
--- a/host/tarball/share/ae3/bin/setup/operator
+++ b/host/tarball/share/ae3/bin/setup/operator
@@ -9,7 +9,7 @@ UserRequireRoot
 USER=$1
 
 if [ ! $USER ]; then
-	echo 'Existing user name is expected'
+	echo 'ERROR: Existing user name is expected' >&2
 	exit 1
 fi
 
diff --git a/host/tarball/share/ae3/bin/which b/host/tarball/share/ae3/bin/which
--- a/host/tarball/share/ae3/bin/which
+++ b/host/tarball/share/ae3/bin/which
@@ -4,7 +4,7 @@
 
 Which(){
 	local COMMAND="$1"
-	[ -z "$COMMAND" ] && echo "Which: COMMAND argument is required!" && exit 1
+	[ -z "$COMMAND" ] && echo "ERROR: Which: COMMAND argument is required!" >&2 && exit 1
 	local CHECK="/usr/local/share/ae3/bin/$COMMAND"
 	[ -f "$CHECK" ] && echo "$CHECK" && return 0
 	return 1
