+ ae3 help [commandName]

diff --git a/host/tarball/share/ae3/bin/help b/host/tarball/share/ae3/bin/help
--- a/host/tarball/share/ae3/bin/help
+++ b/host/tarball/share/ae3/bin/help
@@ -5,6 +5,13 @@ set -e
 . ${0%/*}/../include/subr.sh
 
 
+if [ "$1" != "" ] ; then
+	if [ ! -x "${AE3_BIN}/$1" ] ; then
+		echo "Invalid option: $1" >&2
+		exit 1
+	fi
+	exec "${AE3_BIN}/$1" --help
+fi
 
 echo "AE3 Script commands:"
 
